### PR TITLE
Rebase into latest upstream

### PR DESCRIPTION
**Pull request by PatrykMis**

### CODE REVIEW

**Comment by thestinger** [comment]
Let me know when you've tested it and I'll get it merged.

**Comment by PatrykMis** [comment]
```

Task :brailletranslate:extractPhoneDebugAnnotations

   > Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :talkback project caused this error: /home/runner/work/talkback-foss/talkback-foss/talkback/src/main/libs/screen_understanding.aar

```

Seams we probably have the problem with this upstream. Google forgot to include the source code of screenunderstanding library, providing us with prebuilt .arr file only.

**Comment by PatrykMis** [comment]
@thestinger tested and works.

With exception that this version has all the same bugs like in previous one, but they are speciffic only to open source releases. They just use their own internal libraries in Play Store version like GMS annotations etc.

**Comment by thestinger** [comment]
Isn't it not really open source anymore if they aren't publishing screen_understanding? Seems problematic.

**Comment by PatrykMis** [comment]
Unfortunately. Moreover it's obfuscated.

**Comment by thestinger** [comment]
Can you try to get them to do something about that? They've been incredibly hostile towards previous attempts to do this better though.

**Comment by PatrykMis** [comment]
Rebased to latest upstream which hasn't any .aar file and prebuilts.

**Comment by thestinger** [comment]
@PatrykMis Is this tested? Going to merge it soon.

**Comment by thestinger** [comment]
Seeing a bunch of warnings about tons of strings being removed due to not having a default value. I think this has to be reverted.

**Comment by thestinger** [comment]
Seems that was already an issue before anyway.

**Comment by PatrykMis** [comment]
This issue exists from one and half year, nothing new.

**Comment by thestinger** [comment]
@PatrykMis Can you check that the build I included in external/talkback works?

**Pull request merged**
